### PR TITLE
Add data dictionary basics

### PR DESCRIPTION
**Pull request by jessb0t**
@georgebuzzell First iteration of data dictionary ready for you!  Please see additional notes on Slack. 🤓

### CODE REVIEW

**Comment by jessb0t** [comment]
@georgebuzzell Following our conversation on April 11, I have revised this PR.  Kindly review! 🙏

**Comment by georgebuzzell** [comment]
@jessb0t only other comments:

For the central-tracker_datadict I note that there is no longer a variable for Zoom alone. I.e. to indicate if zoom exists, and if it exists, if usable (i.e. if not poor quality). I don't have strong feelings whether there is a standalone variable for zoom here, for valence, but for other studies in the lab, please do make that the standard. The rationale, is that there is information specific to the zoom file (whether recording quality is usable) that will  apply to most/all variables that reference the zoom file. This is similar to how studies with eeg, we will have a variable for a given eeg recording, and indicate if present or not, and if present, whether it is of ok quality to use (e.g. half cap not disconnected) which is useful to note, distinct from any specific preprocessing that follows. but again, i dont have strong feeling here for the valence study, just for the standard moving forward

in central-tracker_datadic, I also notice some ??? still remaining. Honestly, I think it is fine to approve and move ahead with these still here. We dont have to have everything figured out to start using this. :) HOwever, if easy enough to clarify these now, let's do it (key word is IF). For the questionnaire variables, you have "data-monitor, ???" I think this would just be "code-data-monitor, code-instruments", no? For the variables based on the zoom files, you have "???, manual" which i think would just be "code-data-monitor, manual", rights? And lastly, for the final two variables you have "data-monitor, ???" which i think would just be "code-data-monitor, code-[preprocessing script name for pavlovia task here]" right?

**Comment by georgebuzzell** [comment]
@jessb0t Again, no need to hold up moving ahead with using the data dictionaries for minor details. Please just confirm the changes above, or where you forsee issues, let me know what those are, and the alternative/interim plan/placeholder to move ahead (even if the placeholder is simply ???)

Again, GREAT WORK; thank you!

**Comment by jessb0t** [comment]
@georgebuzzell I love the "code-" idea.  Implemented!

For the Valence central tracker, let's discuss today.  I started to build out the separate Zoom variable, but then I realized that it is only when someone attempts coding that we determine whether the audio is garbled/unusable...so I was trying to avoid making such a person update two cells in the tracker when they encounter such a scenario.  If we include a separate variable for Zoom, then I think we need a separate step of listening to the file to see if it is usable; given the current low number of participants and what I anticipate will be a low percentage of unusable audio, I'm not sure that is the best use of resources since our coders can easily flag unusable audio when they attempt coding, then move on to the next participant.

But I should have clarified that my focus here was on the non-central tracker aspects as I wanted to get these locked down so I could update the "instruments" repo for the summer re-launch of other studies.  So I view the central tracker as very much still "in progress" between you, me, and @F-said!

For now, I am proceeding with this merge based on your comments above.  The data-dico CSV files for these instruments, along with those that you have indicated will be used in the summer launch studies, will be PRed over on that repo later today. 😎

**Pull request merged**
